---
title: "hw3-clarissp"
author: "Clarissa Paz"
date: "9/26/2018"
output: html_document
---

```{r setup, include=FALSE}
require(rgdal)
require(leaflet)
require(leaflet.extras)
require(dplyr)
require(readxl)
require(stringr)
```


```{r}
#Importing data for the map
county2 <- readOGR("Allegheny_County_Boundary.geojson")
senate <- readOGR("Allegheny_County_Pennsylvania_Senate_District_Boundaries.geojson")
wic <- readOGR("Allegheny_County_WIC_Vendor_Locations.geojson")
```


```{r}
icons <- awesomeIconList(
  makeAwesomeIcon(icon = "female", library = "fa", markerColor = "red")
  )

symbology <- colorFactor(c("#738BC1", "#C9705E"), c("R", "D"))

leaflet() %>% 
  setView(lng = -79.995575, lat = 40.4406763, zoom = 10) %>%
  #Basemaps that users can choose from 
  addProviderTiles("Esri.WorldGrayCanvas", group = "Gray Canvas", options = providerTileOptions(noWrap = TRUE)) %>%
  addProviderTiles("CartoDB.DarkMatterNoLabels", group = "Dark Matter", options = providerTileOptions(noWrap = TRUE)) %>%
  addProviderTiles("Esri.WorldTopoMap", group = "Topography", options = providerTileOptions(noWrap = TRUE)) %>%
  
  #Allows users to choose which basemap 
  addLayersControl(
    baseGroups = c("Gray Canvas", "Dark Matter", "Topography"),
    options = layersControlOptions(collapsed = TRUE)
  ) %>%
  addPolylines(data= county2,color = "#292929") %>%
  addPolygons(data = senate, color = ~symbology(as.factor(PARTY))) %>%
  addLegend(position = "bottomright", pal = symbology, values = as.factor(senate$PARTY), title = "Political Party") %>%
  
  addAwesomeMarkers(data = wic, icon = ~icons)


```


```{r}
leaflet(data=county) %>%
  addPolygons()
  
  
```


